package freezy.entities;

public enum PurchaseOrderStatus {
    DRAFT,
    SENT,
    APPROVED,
    PARTIALLY_DELIVERED,
    FULLY_DELIVERED,
    PARTIAL_PAYMENT_RECEIVED,
    FULL_PAYMEMT_RECEIVED,
    PARTIALLY_RECEIVED,
    FULLY_RECEIVED,
    PARTIAL_PAYMENT_DONE,
    FULL_PAYMEMT_DONE,
    CLOSED
}
